#cloud-config
package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-swiftclient
runcmd:
    - pip install celery
    - git clone https://github.com/DrThyme/ACC_Project.git /home/ubuntu/ACC_Project
    - cd /home/ubuntu/ACC_Project
    - export C_FORCE_ROOT="true"
    - export LC_ALL="en_US.UTF-8"
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/geo
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/msh
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/xml
    - chmod -R 777 /home/ubuntu/ACC_Project
