#cloud-config

package_update: true
package_upgrade: true

packages:
    - fenics
    - python-swiftclient
    - git
    - python-pip
    - rabbitmq-server
    - gmsh
runcmd:
    - pip install celery
    - pip install Flask
    - chmod -R 777 /home/ubuntu
    - git clone https://github.com/DrThyme/ACC_Project.git
    - mv ACC_Project home/ubuntu/ACC_Project
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/geo
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/msh
    - mkdir /home/ubuntu/ACC_Project/naca_airfoil/xml
    - chmod -R 777 /home/ubuntu/ACC_Project
    - export LC_ALL=C
    - mkdir bump
